### ISSUE TITLE
Sublime 4149 generates "Error loading syntax file[...]: no such target" pop-up for "JavaScript (Babel)"

### ISSUE THREAD

**Issue by nabijaczleweli** [babel/babel-sublime#427]
![](https://user-images.githubusercontent.com/6709544/236218069-2667b80d-104b-42a3-a014-26d7499db321.png)

And, indeed, I see a 
```yaml
            -   - meta_include_prototype: false
                - match: ''
                  set: scope:source.js.css#at-keyframe-block-content
                  with_prototype:
                    - match: (?=`)
                      pop: true
                    - match: \$\{
                      scope: punctuation.section.interpolation.begin.js
                      push:
                        - clear_scopes: 1  
```
block, and this is the only mention of this in the package.
